language: scala
scala:
  - 2.11.7

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt clean coverage test

after_success:
  - pip install --user codecov && codecov
