language: scala
scala:
  - 2.11.7

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

before_install:
  - pip install --user codecov

after_success:
  - codecov
